create type "public"."order_execution_type" as enum ('normal', 'forecast');

create table "public"."orders" (
    "id" bigint generated by default as identity not null,
    "portfolio_id" bigint not null,
    "isin" text not null,
    "amount" float8 not null,
    "year" bigint not null,
    "month" bigint not null,
    "day" bigint not null,
    "executed_at" date not null,
    "execution_type" order_execution_type not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

CREATE UNIQUE INDEX orders_pkey ON public.orders USING btree (id);

alter table "public"."orders" add constraint "orders_pkey" PRIMARY KEY using index "orders_pkey";

alter table "public"."orders" add constraint "orders_portfolio_id_fkey" FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE not valid;

alter table "public"."orders" validate constraint "orders_portfolio_id_fkey";
