create table "public"."portfolios" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "user_id" bigint not null,
    "isins" jsonb[] null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);

CREATE UNIQUE INDEX portfolios_pkey ON public.portfolios USING btree (id);

alter table "public"."portfolios" add constraint "portfolios_pkey" PRIMARY KEY using index "portfolios_pkey";

alter table "public"."portfolios" add constraint "portfolios_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE not valid;

alter table "public"."portfolios" validate constraint "portfolios_user_id_fkey";
